use_frameworks!

platform :ios, '8.0'

target 'ProtocolDispatcher_Example' do
  pod 'ProtocolDispatcher', :path => '../'

  target 'ProtocolDispatcher_Tests' do
    inherit! :search_paths

    
  end
end
